// created an object "seed" of the specified type
import { createAsparagus } from "./seeds/asparagus.js"
import { createCorn } from "./seeds/corn.js"
import { createPotato } from "./seeds/potato.js"
import { createSoybean } from "./seeds/soybean.js"
import { createSunflower } from "./seeds/sunflower.js"
import { createWheat } from "./seeds/wheat.js"

// addPlant ---- takes a seed object as an argument and pushes it into an empty array. if the argument is an array itself it iterates through the array and adds each object individually
// usePlants simply returns the array of plants that is generated by addPlant
import { addPlant, usePlants } from "./field.js"

export const plantSeeds = (yearsPlantingPlan) => {
    for (const plan of yearsPlantingPlan) {
        for (let j = 0; j < plan.length; j++) {
            if (plan[j] === "Asparagus") {
                addPlant(createAsparagus());
            } else if (plan[j] === "Corn") {
                addPlant(createCorn());
            } else if (plan[j] === "Potato") {
                addPlant(createPotato());
            } else if (plan[j] === "Soybean") {
                addPlant(createSoybean());
            } else if (plan[j] === "Sunflower") {
                addPlant(createSunflower());
            } else if (plan[j] === "Wheat") {
                addPlant(createWheat());
            }
        }
    }
    return usePlants()
}